### ISSUE TITLE
Sentiment text corpus for open source electra sentiment model.

### ISSUE THREAD

**Issue by PhilipMay** [oliverguhr/german-sentiment#3]
Hi @oliverguhr ,
I would like to train and open source a German sentiment model based on our new German Electra Language Model:
https://huggingface.co/german-nlp-group/electra-base-german-uncased

Would you share your preprocessed sentiment training data if I release the work under open source? That would be awsome!

Sincerely,
Philip

**Comment by oliverguhr** [comment]
Hi @PhilipMay,
that sounds great! I am happy to help. I was not aware that you guys are working on this topic too (I used to work for TSI in the past). Anyway, the data is already available :) To download the preprocessed sentiment data, head over to [Zenodo](https://zenodo.org/record/3693810/) and download the "no-scare-balanced.zip" file. Please note that this file does not contain the SCARE data set, due to legal restrictions. If you like to use the scare dataset as well, you need to contact the [author](http://www.romanklinger.de/scare/) to get permission.

Best Regards,
Oliver

PS: I wonder if I should place the download link on a more prominent place?

**Comment by PhilipMay** [comment]
> PS: I wonder if I should place the download link on a more prominent place?

Yes definitly. Please do that.

**Comment by PhilipMay** [comment]
Hey @oliverguhr 
I saw that in the `no-scare-balanced.zip` only the `model.test.full` file has a column on where the data is coming from.
The train and validation dataset is missing this column.

Do you have a dataset where this is also given?

Reopening...

**Comment by oliverguhr** [comment]
I had this data only as an intermediate step and did not publish it, since I only used this information for the validation process. If you need this information, you can re-run the preprocessing script and use the intermediate files. (Or you modify the script).

```
sh download-models-and-data.sh 
cd fasttext
python preprocess.py
```
This script will create following files in "fasttext/modeldata/sets". They are splited by class but you can simply cat them to obtain train, valid and test sets with the dataset tag.

all.test.negative
all.test.neutral
all.test.positive
all.train.negative
all.train.neutral
all.train.positive
all.valid.negative
all.valid.neutral
all.valid.positive
